spring:
  profile.active: prod
  datasource:
       url: ${DATASOURCE_URL}
       username: ${DATASOURCE_USERNAME}
       password: ${DATASOURCE_PASSWORD}
jpa:
  show-sql: false
  properties:
      hibernate:
          format_sql: true

server:
  error:
      include-stactrace: never
api:
  security:
      secret: ${JWT_SECRET:123456}