spring:
  profile.active: dev, prod, test
  datasource:
      url: jdbc:mysql://localhost/vollmed
      username: root
      password: hotrod16
jpa:
   show-sql: true
   properties:
       hibernate:
           format_sql: true

server:
   error:
       include-stactrace: never
api:
   security:
       secret: ${JWT_SECRET:123456}